# Generated by Django 4.0.6 on 2022-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_filminstance_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filminstance',
            name='mark',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='filminstance',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Want to see'), ('a', 'Want to see again'), ('c', 'Completed'), ('n', "Haven't see")], default='w', max_length=1),
        ),
    ]
